# Generated by Django 2.1.15 on 2020-06-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20200611_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_level',
            field=models.CharField(choices=[(1, 'Level 1'), (2, 'Level 2')], default='1', max_length=1),
        ),
    ]
