# Generated by Django 2.1.15 on 2020-06-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_customuser_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_level',
            field=models.CharField(choices=[('1', 'Level 1'), ('2', 'Level 2')], default='1', max_length=1),
        ),
    ]
